name: Deploy Jekyll Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          # bundler-cache: true # This will cache your bundle dependencies

      - name: Install Ruby Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll Site
        env:
          GITHUB_BRANCH: ${{ vars.HEAD }}
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages