url: "https://odichat.app" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Odichat" # the name of your site, e.g. ACME Corp.
tagline: "Automate customer service in WhatsApp with AI agents"
author: "Odisea AI"
description: "Automate up to 70% of customer queries in WhatsApp Business and free up your team for meaningful interactions."
email: "odichat.app@gmail.com"
twitter:
  username: "__andresu__"
  card: "summary"
image: "/assets/images/logo.svg"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin

languages: ["en", "es"]
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]