url: "https://odichat.app" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Odichat" # the name of your site, e.g. ACME Corp.
author: "Odisea AI"
description: "AI Agents for WhatsApp Business"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

tailwindcss:
  config: "./tailwind.config.js"