name: Deploy Jekyll Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true # Enable this for faster builds

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js Dependencies
        run: |
          npm install -D tailwindcss@latest daisyui@latest

      - name: Install Ruby Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll Site
        env:
          GITHUB_BRANCH: ${{ vars.HEAD }}
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages