name: Deploy Jekyll Site

on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true # Enable this for faster builds

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Ruby Dependencies
        run: |
          gem install bundler
          bundle install

      # Add this step to verify Tailwind is installed and processing
      - name: Verify Tailwind Installation
        run: |
          bundle exec tailwindcss --help
          echo "Contents of _site before build:"
          ls -la _site || echo "_site doesn't exist yet"

      - name: Build with Jekyll
        # Add JEKYLL_ENV=production to ensure Tailwind minifies the output
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
          
      # Add these debug steps to inspect the _site directory
      - name: Debug - Show _site contents
        run: |
          echo "=== Contents of _site directory ==="
          ls -la _site/
          echo "=== Contents of _site/assets ==="
          ls -la _site/assets/
          echo "=== Contents of _site/assets/css ==="
          ls -la _site/assets/css/
          echo "=== First few lines of styles.css ==="
          head -n 20 _site/assets/css/styles.css || echo "styles.css not found!"
          echo "=== Size of styles.css ==="
          stat -f %z _site/assets/css/styles.css || echo "Could not get file size!"

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
